### ISSUE TITLE
offset.go() and time.sleep()

### ISSUE THREAD

**Issue by yuvallanger** [benoitc/offset#11]
Hi,

I've tried running this in Python 3:

``` python3
import offset
import time

def f(n):
    time.sleep(n)
    print(n)

offset.go(f(2))
offset.go(f(1))
```

It prints:

```
2
1
```

the equivalent in Golang would have printed:

```
1
2
```

**Comment by yuvallanger** [comment]
Oh, silly me.

``` python3
from offset import maintask, run, go, time

def f(n):
    time.sleep(n*time.SECOND/3)
    print(n)

@maintask
def main():
    go(f, 2)
    go(f, 1)
    print(2,1)


if __name__ == "__main__":
    run()
```

This works, but with many "wait" printed, like this:

```
$ python3 poop.py 
2 1
wait
wait
wait
wait
wait
wait
wait
1
wait
wait
wait
wait
wait
wait
wait
2
```

**Comment by limodou** [comment]
I also saw "wait" output, it's a print statement in context.py, maybe it's a debug print line which not deleted yet I think.

**Comment by benoitc** [comment]
hrm yeah will remove that later today. I plan to release the new channel
backend based on mmap on wed also.

**Comment by limodou** [comment]
Great!
