### ISSUE TITLE
error running "python setup.py install" in virtualenv 

### ISSUE THREAD

**Issue by handloomweaver** [benoitc/offset#5]
error: can't copy 'MANIFEST.in': doesn't exist or not a regular file

Sorry I might be stupid. What is the correct way to install the offset library?

**Comment by benoitc** [comment]
the file was missing. fixed in f70a967e39fd6d438428b05a8a36b99b4a44afd5 . thanks for the feedback :)

**Comment by handloomweaver** [comment]
Now getting "error: can't copy 'UNLICENSE': doesn't exist or not a regular file"!

**Comment by benoitc** [comment]
just fixed sorry. Oddly it wasn't raised on my machine.
